wowarenalogs/wowarenalogs

package-lock.json
packages/app/src/main.ts
packages/desktop/components/DesktopLayout/index.tsx
packages/shared/package.json
packages/shared/src/components/CombatReport/CombatCurves/CurveChart.tsx
packages/shared/src/components/CombatReport/CombatCurves/PlayerCurves.tsx
packages/shared/src/components/CombatReport/CombatCurves/TeamCurves.tsx
packages/shared/src/components/CombatReport/CombatCurves/constants.ts
packages/shared/src/components/CombatReport/CombatCurves/index.tsx
packages/shared/src/components/CombatReport/index.tsx
packages/shared/src/components/MainLayout/index.tsx
packages/shared/src/components/Test/index.tsx
packages/shared/src/index.ts

curves tab

---

packages/shared/src/components/CombatReport/CombatUnitTimelineView.tsx

LOL finally found what's the bug

finally fix timeline bleeding out bug

---

packages/shared/src/utils/utils.ts

ilvl should not have fractions.

round up ilvl numbers

---

packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx
packages/shared/src/components/CombatReport/SpellIcon.tsx

implement player stats charts

---

packages/desktop/pages/settings.tsx

allow setting wow directory in settings page

---

.github/workflows/release-app.yml
package-lock.json
package.json
packages/app/package.json
packages/app/src/main.ts
packages/app/src/nativeBridge/modules/applicationModule.ts
packages/shared/src/types/nativeBridge.ts

electron-updater does not require code-sign for windows builds. trying this to mitigate our problem.

use electron-builder to publish app release

---

packages/shared/src/components/CombatReport/CombatReplay/ReplayEvents/index.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView.tsx
packages/shared/src/utils/utils.ts

add more info to timeline view

---

packages/desktop/components/LatestMatchMonitor/index.tsx

add troubleshooting tips

---

packages/shared/src/components/CombatReport/CombatCurves/CurveChart.tsx

Prior to this the curves will not resize if you make the window smaller
Resizing is still pretty slow
Discussions:
https://github.com/recharts/recharts/issues/172
https://github.com/recharts/recharts/issues/1767

Resolution for issue where downsizing will not resize charts

---

packages/shared/src/components/CombatReport/CombatLogView/index.tsx
packages/shared/src/components/CombatReport/index.tsx

Simple log view for debugging

---

package-lock.json
packages/desktop/package.json
packages/desktop/pages/history.tsx
packages/desktop/pages/search.tsx
packages/shared/package.json
packages/shared/src/components/CombatReport/index.tsx
packages/shared/src/components/CombatStubList/index.tsx
packages/shared/src/components/CombatStubList/rows.tsx
packages/shared/src/components/MainLayout/index.tsx
packages/shared/src/components/MatchSearch/BracketSelector.tsx
packages/shared/src/components/common/CombatReportFromStorage.tsx
packages/shared/src/components/common/LoadingPage.tsx

back button now does what it's intuitively supposed to do.

improve back button behavior on combat reports

---

packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx
packages/shared/src/components/CombatReport/CombatPlayers/TalentDisplay.tsx

ui improvements on player tab

---

packages/shared/src/components/CombatReport/CombatSummary/Meters.tsx
packages/shared/src/components/CombatReport/index.tsx
packages/web/components/WebLayout/index.tsx
packages/web/pages/match.tsx

improve match page ux

---

packages/shared/src/components/CombatReport/CombatUnitHpUpdate.tsx
packages/shared/tailwind.config.js

print number on big damage/heals in timeline view

---

packages/desktop/styles/globals.css
packages/shared/src/components/CombatReport/CombatUnitHpUpdate.tsx
packages/shared/src/components/CombatReport/CombatUnitName.tsx
packages/web/styles/globals.css

some of our images look blurry in electron because of antialiasing not working well by default when image is scaled down. This fixes it

fix blurry images

---

packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx

Simple spell frequency

---

packages/desktop/pages/_app.tsx
packages/web/pages/_app.tsx

Causes Apollo client queries to refetch more often, current behavior they are very very lazy

aggro refetches

---

packages/shared/src/components/CombatReport/CombatPlayers/TalentDisplay.tsx

fix druid talent display height

---

packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx

fix player stats table cell size

---

packages/desktop/pages/index.tsx
packages/desktop/pages/settings.tsx
packages/desktop/pages/upgrade.tsx

people who are on native app that's before 4.0.2 doesn't have auto-update, and would be pretty buggy. this will prompt people to upgrade.

show upgrade message at startup for old app version

---

packages/shared/src/components/MatchSearch/RatingSelector.tsx
packages/shared/src/graphql-server/resolvers/matches.ts

tweak tier gating on community matches

---

package-lock.json
packages/cloud/index.js
packages/cloud/package.json
packages/cloud/serverless.prod.yml
packages/cloud/src/refreshCompetitiveStatsHandler.ts
packages/cloud/test/test_refresh_competitive_stats.ts

See https://console.cloud.google.com/storage/browser/data.public-dev.wowarenalogs.com;tab=objects?project=wowarenalogs-public-dev&prefix=&forceOnObjectsSortingFiltering=false for the data generated from this. Once deployed to prod we can trigger this daily

generate daily competitive stats

---

packages/shared/src/components/CombatReport/CombatScoreboard/index.tsx
packages/shared/src/components/CombatReport/index.tsx

Basic info for scoreboard

---

package-lock.json
packages/desktop/pages/api/blizzard/[...route].ts
packages/shared/package.json
packages/shared/src/api/blizzardApi.ts
packages/shared/src/components/CombatReport/AchievementBadge/index.tsx
packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx
packages/shared/src/utils/realms.ts
packages/web/pages/api/blizzard/[...route].ts

Restore achievement lookup functionality
This is a rewrite from the old badge function and no longer relies on hard-coded achievement ids! It does however rely on some naming and conventions around the achievements. Could be issues in other languages?

Achievements badge

---

packages/shared/src/components/CombatReport/CombatCurves/CurveChart.tsx

shorter numbers on graphs

---

packages/shared/src/components/CompetitiveStats/index.tsx
packages/shared/src/components/common/SpecImage.tsx
packages/shared/src/components/pages/StatsPage.tsx

implement comp stats tab

---

packages/cloud/src/refreshCompetitiveStatsHandler.ts

```json
{
"2v2": {
"0": {
"lose": {
"matches": 68,
"effectiveDps": 0,
"effectiveHps": 0
}
},
"62": {
"lose": {
"matches": 131,
"effectiveDps": -12255.338993314315,
"effectiveHps": 5982.1598403583575
},
"win": {
"matches": 92,
"effectiveDps": -24331.574087579007,
"effectiveHps": 5636.772734862012
}
},
"63": {
"lose": {
"matches": 46,
"effectiveDps": -12614.941319566668,
"effectiveHps": 9015.956910683333
},
"win": {
"matches": 40,
"effectiveDps": -24258.460136204547,
"effectiveHps": 6563.2549648125
}
},
"64": {
"lose": {
"matches": 118,
"effectiveDps": -13438.278358757143,
"effectiveHps": 7717.059112225228
},
"win": {
"matches": 81,
"effectiveDps": -21165.467698563938,
"effectiveHps": 6406.773717523019
}
},
"65": {
"lose": {
"matches": 186,
"effectiveDps": -2773.2902353772024, …
```

calculate dps and hps stats per spec

---

packages/shared/src/components/CompetitiveStats/index.tsx
packages/shared/src/components/common/SpecImage.tsx
packages/shared/src/components/pages/StatsPage.tsx

enable sorting by win rate on stats page

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/CompetitiveStats/common.tsx
packages/shared/src/components/pages/StatsPage.tsx

show dps and hps stats

---

packages/shared/src/components/MatchSearch/SpecSelector.tsx

Fix pixel bug on borderS

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/pages/StatsPage.tsx
packages/web/pages/index.tsx

make stats page work well on mobile

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/CompetitiveStats/common.tsx

show first blood stats

---

packages/shared/src/components/CombatReport/index.tsx
packages/shared/src/components/common/DownloadPromotion.tsx
packages/shared/src/components/pages/StatsPage.tsx

promote download on stats page

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx

show burst dps on stats

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/CompetitiveStats/common.tsx

adjust win rate for uploader bias

---

packages/shared/src/utils/utils.ts

fix combat number display bug

---

packages/shared/src/components/CombatReport/CombatReplay/ReplayUnitFrames/UnitSpellTracker.module.css
packages/shared/src/components/CombatReport/CombatReplay/ReplayUnitFrames/UnitSpellTracker.tsx
packages/shared/src/components/CombatReport/SpellIcon.tsx

Fix some awc icon css from tw migration

---

packages/shared/src/components/CombatReport/CombatUnitTimelineView.tsx

fix timeline alignment bug

---

packages/shared/src/components/CombatReport/CombatCurves/index.tsx

curves default to friend team

---

packages/desktop/hooks/LocalCombatsContext/index.tsx

this will unblock https://github.com/wowarenalogs/wowarenalogs/pull/172

log shuffle round mmr

---

packages/shared/src/data/spells.json

another round of refresh. seems bigdebuff cleaned up lots of SL spells and added more evoker stuff.

refresh bigdebuff data

---

packages/app/src/nativeBridge/modules/filesModule.ts

we heard people complain about not knowing what path to select as wow folder. This should make it more clear.

make folder selector more clear

---

packages/shared/src/components/CombatReport/CombatReplay/ReplayDampeningTracker.tsx
packages/shared/src/components/CombatReport/CombatSummary/Meters.tsx
packages/shared/src/components/CombatReport/CombatUnitHpUpdate.tsx
packages/shared/src/utils/dampening.ts

show latest dampening value on summary view

---

packages/shared/src/components/CombatReport/CombatReplay/ReplayUnitFrames/UnitFrame.tsx
packages/shared/src/components/CombatReport/CombatSummary/Meters.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitAuraTimeline.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitHpUpdate.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/common.ts
packages/shared/src/components/CombatReport/CombatUnitTimelineView/index.tsx
packages/shared/src/data/spellTags.ts
packages/shared/src/utils/auras.ts

implement aura timeline on death view

---

packages/shared/src/components/CombatReport/CombatCC/index.tsx
packages/shared/src/components/CombatReport/CombatReportContext.tsx
packages/shared/src/components/CombatReport/index.tsx

implement cc and kicks tab

---

packages/cloud/src/refreshCompetitiveStatsHandler.ts
packages/shared/src/components/pages/StatsPage.tsx

look back 7 days of stats

---

packages/shared/src/components/CombatReport/CombatReplay/ReplayCharacter.tsx
packages/shared/src/components/CombatReport/CombatReplay/ReplayHealthBar.tsx
packages/shared/src/components/CombatReport/CombatReplay/index.tsx

Replay fixes

---

package.json
packages/app/src/nativeBridge/modules/applicationModule.ts
packages/desktop/pages/profile.tsx
packages/shared/src/components/common/LogoutButton.tsx
packages/shared/src/components/pages/ProfilePage.tsx
packages/shared/src/types/nativeBridge.ts
packages/web/pages/profile.tsx

tested a full logout and log back in flow. it works as expected. battle.net identity was fully cleared and need to re-enter password.

clear storage on logout

---

packages/cloud/src/refreshCompetitiveStatsHandler.ts

this can't be merged yet. need to wait till we fix SS MMR records

rating buckets in stats

---

packages/cloud/src/refreshCompetitiveStatsHandler.ts

Reverts wowarenalogs/wowarenalogs#172
something terribly wrong in the numbers after this

Revert "rating buckets in stats"

---

packages/shared/src/components/CombatReport/CombatSummary/Meters.tsx
packages/shared/src/components/CombatReport/CombatSummary/index.tsx
packages/shared/src/components/CombatReport/CombatUnitName.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitAuraTimeline.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitHpUpdate.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/index.tsx

Improve death log UI

---

packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitHpUpdate.tsx
packages/shared/src/components/CombatReport/CombatUnitTimelineView/index.tsx

merge damage from same spell on timeline

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx

stats are getting incorrect numbers somehow since 1/30.

use a fixed date for stats temporarily

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx

This reverts commit a624b728c09fb25af143d9a2ed9d81bd04e58109.

Revert "use a fixed date for stats temporarily"

---

packages/shared/src/components/CombatReport/CombatUnitTimelineView/index.tsx

show absolute time on mouse hover death time mark

---

packages/desktop/components/DesktopLayout/index.tsx

this particular error is mostly images failing to load and it's overloading our sentry capacity.

tweak sentry config to avoid overload

---

packages/shared/src/data/talentIdMap.json

src https://www.raidbots.com/static/data/live/talents.json

update talent base file

---

packages/cloud/prisma/migrations/20230214053035_date_bracket_index/migration.sql
packages/cloud/prisma/schema.prisma
packages/cloud/src/refreshCompetitiveStatsHandler.ts

see https://console.cloud.google.com/storage/browser/_details/data.public-dev.wowarenalogs.com/data/spec-stats/2v2/0-4999.v3.latest.json;tab=live_object?project=wowarenalogs-public-dev as a sample output

use sql to query spec stats

---

packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/pages/StatsPage.tsx

support rating ranges for spec stats

---

packages/shared/src/components/CombatReport/CombatUnitTimelineView/index.tsx

implement a slider on death view

---

packages/cloud/src/refreshCompetitiveStatsHandler.ts
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/CompetitiveStats/SpecTrendChart.tsx
packages/shared/src/components/CompetitiveStats/common.tsx
packages/shared/src/components/pages/StatsPage.tsx
packages/shared/src/utils/utils.ts

implement trend lines on spec stats page

---

packages/shared/src/components/CombatReport/CombatPlayers/CheckPvPLink.tsx

fix checkpvp link when server name has space

---

packages/parser/src/CombatData.ts

Also attribute absorbs that pets emit to their owner

---

packages/parser/src/CombatData.ts
packages/parser/src/CombatUnit.ts
packages/parser/test/effectiveAmount.test.ts
packages/parser/test/parser.test.ts
packages/parser/test/pipelineComponents.test.ts
packages/shared/src/components/CombatReport/CombatCurves/constants.ts
packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx

Feed absorbs into damage stream

---

packages/shared/src/components/CombatReport/CombatReportContext.tsx
packages/shared/src/components/CombatReport/CombatSummary/Meters.tsx

Somewhat crude mock-up for Aug contributions

---

package-lock.json
packages/cloud/src/utils.ts
packages/cloud/src/writeMatchStubHandler.ts
packages/shared/package.json
packages/sql/prisma/schema.prisma

this look up will be used to display user personal stats (where we need to know which characters belong to the user)

store user character lookup

---

packages/app/src/nativeBridge/module.ts

Fixes docstrings on tooltips (less indirection)

Clean type

---

packages/shared/src/components/CompetitiveStats/CompStats.tsx
packages/shared/src/components/CompetitiveStats/SpecStats.tsx
packages/shared/src/components/CompetitiveStats/TierList.tsx
packages/shared/src/components/pages/StatsPage.tsx
packages/shared/src/utils/dampening.ts
packages/shared/src/utils/utils.ts

display tier list on stats page

---

packages/app/src/nativeBridge/modules/obsModule.ts
packages/app/src/preloadApi.ts
packages/app/src/windowApi.d.ts
packages/desktop/components/Settings/RecordingSettings.tsx
packages/desktop/hooks/LocalCombatsContext/index.tsx

Configure capture modes

---

packages/desktop/components/Settings/RecordingSettings.tsx
packages/desktop/pages/settings.tsx

ux tweak on video recording settings

---

package.json
packages/recorder/package.json
packages/recorder/tsconfig.json

recorder package is a pure lib so can be referenced directly as src ts files

simplify recorder build process

---

package.json
packages/app/src/nativeBridge/modules/obsModule.ts
packages/app/src/preloadApi.ts
packages/app/src/windowApi.d.ts
packages/desktop/components/DesktopLayout/index.tsx
packages/desktop/components/Settings/RecordingSettings.tsx
packages/desktop/hooks/AppConfigContext/index.tsx
packages/desktop/hooks/VideoRecordingContext/index.tsx
packages/desktop/pages/settings.tsx
packages/recorder/src/recorder.ts
packages/recorder/src/types.ts

auto start obs engine

---

package.json
packages/recorder/src/recorder.ts

ref https://github.com/aza547/wow-recorder/commit/07509258ee626c8562c2ed6917b2327634e6050e
Change made in anticipation of combat log flush being deferred

Increase buffer time

---

package.json
packages/app/src/nativeBridge/modules/logsModule/logWatcher.ts

finally got linux fully working

fix file watcher on linux

---

packages/desktop/components/LatestMatchMonitor/index.tsx
packages/web/pages/index.tsx

add download link for linux

---

packages/desktop/components/LatestMatchMonitor/index.tsx

Show update banner

---

packages/desktop/components/Settings/RecordingSettings.tsx

Full audio mixing options

---

packages/desktop/pages/awc.tsx
packages/shared/src/components/MainLayout/index.tsx
packages/shared/src/components/MatchSearch/BracketSelector.tsx
packages/shared/src/components/pages/AWCPage.tsx
packages/shared/src/data/awc/EU_TWW_S1C1.json
packages/shared/src/data/awc/NA_TWW_S1C1.json
packages/shared/src/data/awc/types.ts
packages/shared/src/utils/featureFlags.ts
packages/web/pages/awc.tsx

Awc preview

---

packages/shared/src/components/CombatReport/CombatTimeline/MultiPlayerTimeline.tsx
packages/shared/src/components/CombatReport/CombatTimeline/index.tsx
packages/shared/src/components/CombatReport/index.tsx

Timeline analysis tool to more quickly review openers / cc chains

Timeline v
