- packages/shared/src/components/CombatReport/CombatSummary/index.tsx
previously <td> automatically places the child vertically centered. now it snaps to the top -
> quick fix for the death timeline on summary page

- packages/shared/src/hooks/useCombatFromStorage.ts
this can cause the useQuery to infinitely retry
> fix a nullptr bug

- packages/desktop/pages/_app.tsx
Turned this off to reduce the re-querying of stuff initially but I don't think the UX has been good.
I've noticed my match history goes stale for much much longer than I'd like. Until we can code something more sophisticated this should help a lot.
> Refetch queries on window focus

- packages/shared/src/components/CombatReport/CombatCurves/constants.ts
tried 1.5 and it was not good - half-seconds don't display well on the x-axis and looks confusing. Use 2s for now.
> change curves interval to 2s

- README.md
- packages/cloud/package.json
- packages/cloud/serverless.dev.yml
- packages/cloud/serverless.prod.yml
- packages/cloud/src/operations/generateMapImage.ts
- packages/cloud/src/refreshSpellIconsHandler.ts
- packages/cloud/src/writeAnonLogHandler.ts
- packages/cloud/src/writeMatchStubHandler.ts
- packages/cloud/test/test_file_upload.ts
- packages/cloud/test/test_indexes.ts
- packages/desktop/pages/api/auth/[...nextauth].ts
- packages/shared/src/api/combatUploadSignatureHandler.ts
- packages/shared/src/components/common/ErrorPage.tsx
- packages/shared/src/graphql-server/resolvers/matches.ts
- packages/shared/src/graphql-server/utils/getUserProfileAsync.ts
- packages/shared/src/graphql-server/utils/setUserReferrerAsync.ts
doing a few things in this PR -
* we now consistently use a json file as GCP credential. one json file to rule them all.
* got rid of the different table/bucket names between dev vs prod, since we are separate them at GCP project level
* added instructions in README to help contributors get started
> make the repo more friendly to contributors

- packages/cloud/src/createMatchStub.ts
- packages/desktop/components/DesktopLayout/index.tsx
- packages/desktop/components/FirstTimeSetup/index.tsx
- packages/desktop/hooks/LocalCombatsContext/index.tsx
- packages/desktop/pages/search.tsx
- packages/parser/src/utils.ts
- packages/shared/src/api/combatUploadSignatureHandler.ts
- packages/shared/src/components/CombatReport/index.tsx
- packages/shared/src/hooks/AuthContext/index.tsx
- packages/shared/src/utils/upload.ts
I think we can implement most of our stats features through google analytics reporting API once these events are in.
google analytics automatically batches events which is nice - 
en=event_NewMatchProcessed&_ee=1&ep.wowVersion=retail&ep.combatId=806f6f59e89c33c8a221f56e9d2175c4&ep.date=2022-12-22&ep.bracket=Rated%20Solo%20Shuffle&ep.zoneId=2547&epn.durationInSeconds=42.296&epn.averageMMR=0&ep.winningTeamSpecs=256_70_71&ep.losingTeamSpecs=1468_267_72&ep.singleSidedSpecIndices=%7C256%7C70%7C71%7C256_70_71%7C1468%7C267%7C72%7C1468_267_72%7C
en=event_NewCompRecord&_ee=1&ep.wowVersion=retail&ep.combatId=806f6f59e89c33c8a221f56e9d2175c4&ep.date=2022-12-22&ep.bracket=Rated%20Solo%20Shuffle&ep.zoneId=2547&epn.durationInSeconds=42.296&epn.averageMMR=0&ep.specs=256_70_71&ep.result=win …
> log match stats to google analytics

- packages/desktop/next.config.js
- packages/web/next.config.js
next/image by default uses a middle tier end point to serve images which is significantly slowing down the performance. This will make it so that we hit CDN directly instead of going through the middle tier, because most of these images are just class/spec/spells which don't need much optimization (which mainly does resizing to save network bandwidth)
> use unoptimized images

- packages/shared/src/components/CombatReport/CombatPlayers/index.tsx
- packages/shared/src/components/CombatReport/index.tsx
now that player tab is pretty tall, users would have to do a lot of scrolling and it's convenient to make the players list sticky so it stays in viewport regardless of scroll offset.
> make player list sticky on players tab

- packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx
the player tab is getting increasingly crowded. doing this to mitigate vertical space and medium size looks pretty good. at some point we might need tabbing there.
> reduce size of gear icons in player tab

- packages/shared/src/components/CombatReport/CombatReplay/ReplayEvents/ReplayEventDisplay.tsx
- packages/shared/src/components/CombatReport/CombatReplay/ReplayEvents/ReplayEventFilterDropdown.tsx
- packages/shared/src/components/CombatReport/CombatReplay/ReplayEvents/index.tsx
Before:
Option:
After:
This mode changes the events log to only show casted spells -- effectively making it a display of how the caster used their GCDs. The standard log is fairly confusing due to the high number of procs/double effects like overload that pollute the list. It can be challenging to tell how a player is actually setting up their burst
> Experimental gcds only mode for replay events

- packages/shared/src/components/CombatReport/CombatReportContext.tsx
there's a bug sometimes a neutral unit would show up as a player. 
a deeper fix might need to happen in the parser but this would solve most of the visible problems
> fix neutral unit showing as a player

- packages/cloud/src/refreshCompetitiveStatsHandler.ts
for spec stats, added isKillTarget which is the likelihood of this spec being first blood
for comp stats, added effective dps, effective hps and the breakdown of kill target spec (which spec is most likely the kill target in each comp)
```json
"256_259": {
"win": {
"matches": 280,
"effectiveDps": 39675.42065132331,
"effectiveHps": 36396.11676413033
},
"lose": {
"matches": 227,
"effectiveDps": 30597.261271104755,
"effectiveHps": 30607.103143766668,
"killTargetSpec": {
"256": 14,
"259": 25
}
}
}
```
> add dps, hps and kill target stats

- packages/web/pages/matches/user/[userId].tsx
Simple user history, internal use only atm (not linked anywhere)
> Simple user history

- packages/shared/graphql.schema.json
- packages/shared/src/graphql-server/resolvers/index.ts
- packages/shared/src/graphql-server/resolvers/matches.ts
- packages/shared/src/graphql-server/types/gql.ts
- packages/shared/src/graphql/__generated__/graphql.ts
- packages/shared/src/graphql/queries.graphql
- packages/web/pages/matches/character/[characterName].tsx
-May contain same-name-same-realm-name entries for characters that exist in EU/US/etc realms. Factoring them out isn't simple right now because the region isn't recorded on the stub and the base data isn't in the log. We'd have to add a header to stitch it into metadata similar to timezone. Seems like a big lift for very little reward - the number of exact name/realm matches should be very very low
> A simple system for looking up history by charname and realm

- packages/desktop/pages/history.tsx
- packages/shared/src/components/common/SignInPromotion.tsx
- packages/shared/src/components/pages/ProfilePage.tsx
- packages/web/pages/history.tsx
currently the history page is completely empty for people who have not signed in. We've heard a few users complain it's confusing. This will show a sign in prompt.
> promote sign in on history page for unauthenticated users

- packages/shared/src/data/spellTags.ts
lots of insignificant buffs/debuffs are shown on the replay map view. bigdebuff provided a flag for us to exclude them so making use of it.
> hide insignificant auras on replay

- packages/shared/src/components/CombatReport/CombatReplay/ReplayUnitFrames/UnitSpellTracker.tsx
- packages/shared/src/components/CombatReport/SpellIcon.tsx
Allow AWC icons to track full aura duration
Show icon as 'active' for 500ms after casting to let instant auras like medallion work well
Cooldown tracking overall is still not perfect, procs of stuff like Avatar can trick it
> Update awc auras to track duration and add a just-casted state

- packages/shared/src/components/CombatReport/CombatReplay/ReplayUnitFrames/UnitFrame.tsx
Fix some issues with mana bars.
This PR manually assigns each spec a power type to track as their 'mana bar'. Previously specs with multiple resource types (most hybrids) would have buggy displays on their mana bar as the different power type events fired.
There were also several cases (again, mostly for hybrids) where the mana bar disappeared entirely due to an ability firing that didn't consume power.
> Draft fix for MP bars

- packages/cloud/src/refreshCompetitiveStatsHandler.ts
apparently, calculating average value through GA is very unreliable. calculating sum of the numerator and denominator separately is giving much more consistent results. 
pick ret paladin stats in 2s as example:
using average - 2023-01-25
```json
{
"lose": {
"matches": 1089,
"effectiveDps": 20988.103974068003,
"effectiveHps": 8823.23409059669,
"isKillTarget": 0.6042240587695134,
"burstDps": 133829.25570331683
},
"win": {
"matches": 870,
"effectiveDps": 33265.368247626626,
"effectiveHps": 8894.698457811162,
"isKillTarget": 0.01954022988505747,
"burstDps": 164578.80550756268
}
}
```
using average - 2023-02-01
```json
{
"lose": {
"matches": 662,
"effectiveDps": 10658.13090955438,
"effectiveHps": 4675.602709016615,
"isKillTarget": 0.6148036253776435,
"burstDps": 60860.62034241388
},
"win": { …
```
> fix average stats

- packages/shared/src/components/CombatReport/CombatUnitTimelineView/CombatUnitHpUpdate.tsx
> Look up owner of action to determine true color of damage tick

- packages/shared/src/components/CompetitiveStats/CompStats.tsx
- packages/shared/src/components/CompetitiveStats/SpecStats.tsx
data.wowarenalogs.com is done through cloudflare cdn without depending on load balancer on google cloud. next i'll swap out images.wowarenalogs.com as well, and then we can get rid of the google cloud networking cost.
> use data.wowarenalogs.com to query stats files

- packages/app/src/main.ts
- packages/app/src/nativeBridge/modules/applicationModule.ts
- packages/app/src/nativeBridge/modules/common/globalStates.ts
- packages/app/webpack.preload.config.js
- packages/desktop/components/TitleBar/index.tsx
- packages/shared/src/types/nativeBridge.ts
currently if you launch the app, minimize it to system tray, and try launching the app again, it will show a frozen window which looks broken. 
this PR makes is so that the second instance will terminate and the hidden window from the first app instance will show up.
another issue discovered here is that because of the previous minimize-to-system-tray behavior, now it's really hard to trigger app update. because people may forget to ever properly quit the app. so made another change to remind people of app update more explicitly.
> fix second-instance behavior

- packages/shared/src/components/CombatReport/CombatPlayers/CheckPvPLink.tsx
- packages/shared/src/components/CombatReport/CombatPlayers/CombatPlayer.tsx
In rare cases pets could use abilities that had the same spell id which would cause a dupe-key warning from React
> Fix check pvp link, rare bug with spell keys

- packages/shared/src/components/CombatStubList/rows.tsx
Shuffle rounds that were still local ended up without ids which caused the match loader to fail
ref: https://discord.com/channels/797758027875876865/797759589591678987/1161649022122078228
> Fix issue where local shuffle rounds caused an error

- packages/shared/src/components/CombatReport/CombatVideo/index.module.css
- packages/shared/src/components/CombatReport/CombatVideo/index.tsx
- packages/shared/src/components/CombatReport/index.tsx
timestamp sync implemented from native side
buttons to restart round and skip to last 5 seconds
crude progress bar to show round overall time
controls still present in video to provide easier viewing if you already know all the hotkeys
> Video UX v1

- packages/desktop/components/Settings/RecordingSettings.tsx
Half-fix for https://github.com/wowarenalogs/wowarenalogs/issues/297
Still need to address clipping of the resolution dropdown off the page
Also a technical note: z-index will not resolve the layering issue since the preview window is being drawn by a process outside of the normal css/dom loop
> Move preview to the right to get out of the way of dropdowns

- package.json
- packages/app/src/nativeBridge/modules/obsModule.ts
- packages/app/src/preloadApi.ts
- packages/app/src/windowApi.d.ts
- packages/desktop/components/Settings/RecordingSettings.tsx
- packages/desktop/hooks/VideoRecordingContext/index.tsx
- packages/parser/test/soloshuffle.test.ts
Allow users to edit encoding settings for OBS
Uses the lib obs query to get encoder options and then intersects that with the list of explicitly supported encoders to limit the user choices fairly conservatively. On my machine lib-obs exposes 9 options but some of them have lots of weird errors.
> Simple encoding settings

- packages/desktop/components/DesktopLayout/index.tsx
- packages/desktop/components/LatestMatchMonitor/index.tsx
- packages/desktop/hooks/AppConfigContext/index.tsx
- packages/desktop/hooks/LocalCombatsContext/index.tsx
- packages/desktop/pages/settings.tsx
- packages/shared/src/components/CombatReport/index.tsx
- packages/shared/src/hooks/ClientContext/index.tsx
- packages/shared/src/index.ts
- packages/shared/src/utils/featureFlags.ts
- packages/web/components/WebLayout/index.tsx
Flags exposed through clientContext which inherits locally-defined flags from appConfig; for web these are empty for now but in theory we could use cookies/localstorage to carry flags if needed
Simple cli-like utility to add/drop feature flags
Some consolidation of logic to use the remote flags on the user model in firebase as well
> quick and dirty impl to get hidden feature flags

- packages/parser/src/utils.ts
- packages/parser/test/3v3.test.ts
- packages/parser/test/bgblitz.test.ts
- packages/parser/test/soloshuffle.test.ts
This function was responsible for insane memory allocations -- I think originally I had thought String.slice(n) would pull the first n chars but it actually pulls char n to the last to char. This means the md5 hash was receiving almost the entire log file as input for hashing which in addition to being unintentional was massive overkill.
Profiling an execution where I parsed 4 of our test logs I went from ~170mb total heap down to 80mb total heap (per `{ memoryUsage } from 'node:process'`) results)
This will cause some duplication to be possible during the transition, it's not something I think is critical to address though.
> Change hashing to be lighter
